name: SmartActors
title: SmartActors Docs
description: > # this means to ignore newlines until "baseurl:"
  Here are some examples and tutorials how to use SmartActors library.
baseurl: "/tutorials"
url: "https://smarttools.github.io"
github_username:  SmartTools
encoding: utf-8

VERSION: 0.6.0

ASSET_PATH: false

# Build settings
markdown_ext: "md"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: /:categories/:year/:month/:day/:title
highlighter: rouge
gems:
  - jekyll-feed
  - just-the-docs

# theme: 'just-the-docs'
remote_theme: "just-the-docs/just-the-docs"

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
heading_anchors: true

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

keep_files:
  - src/
